name: comicsawy
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # Default icons asset for Apple icons
    cupertino_icons: ^1.0.2

    # enabling connecting to Firebase core, storage, and auth
    firebase_core: ^2.24.2
    firebase_storage: ^11.6.0
    firebase_auth: ^4.16.0

    # audio player
    just_audio: ^0.9.29

    # to store simple data locally
    shared_preferences: ^2.2.0

    # annotating for json_serializable
    json_annotation: ^4.8.0

    # networking
    retrofit: ^4.2.0
    dio: ^5.8.0+1

    # dio log prettier
    pretty_dio_logger: ^1.3.1

    # to pic files from phone storage
    file_picker: ^5.3.1

    # A flutter plugin for adapting screen and font size (Responsive)
    flutter_screenutil: ^5.7.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

    # retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit
    retrofit_generator: ^6.0.0+3

    # A build system for Dart code generation and modular compilation
    # useful terminal command: flutter pub run build_runner build
    # useful terminal command: flutter pub run build_runner build --delete-conflicting-outputs
    build_runner: ^2.3.3

    # Automatically generate code for converting to and from JSON by annotating Dart classes.
    json_serializable: ^6.6.1

    #To customize Flutter's splash screen with background color and splash image
    # useful terminal command: flutter pub run flutter_native_splash:create
    flutter_native_splash: ^2.2.18

flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    fonts:
        - family: mikhak
          fonts:
              - asset: assets/fonts/title/arfonts-mikhak-bold.ttf
                weight: 700
        - family: khebrat
          fonts:
              - asset: assets/fonts/read/Khebrat-Musamim-Regular.ttf

    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
